# Generated by Django 4.2.16 on 2024-09-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
