# Generated by Django 4.2.16 on 2024-09-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_specialization_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='fee',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
