# Generated by Django 4.2.16 on 2024-09-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_specialization_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='fee',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
