# Generated by Django 4.2.16 on 2024-10-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_doctoravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='start_time',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='time_slots',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day',
            field=models.DateField(),
        ),
    ]
