# Generated by Django 4.2.16 on 2024-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_doctoravailability_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mode_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('temp', 'Temporary'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no-show', 'No Show')], default='temp', max_length=20),
        ),
    ]
