# Generated by Django 4.2.16 on 2024-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_medicalhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='summary',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='allergies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='diagnoses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='diet_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='medications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='past_surgeries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='physical_therapy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
