# Generated by Django 4.2.16 on 2024-10-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_medication_doctor_remove_medication_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
    ]
