# Generated by Django 4.2.16 on 2024-10-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_prescription_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mode_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=50),
        ),
    ]
